sudo: required
language: c
dist: trusty
matrix:
  include:
    - os: linux
      env: TOOL=doxygen
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cmake
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_API_TOKEN
        local_dir: doxygen/html
        on:
          branch: master-doc
before_install:
 
install:

before_script: 

script:
  - if [ $TOOL == "doxygen" ]; then doxygen Doxyfile; fi
after_script:
  
notifications:
 # email: false
