name: CI on linux

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master

jobs:
  ubuntu_16.04_cmake:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        EVENT_CMAKE_OPTIONS: ["","-DEVENT__DISABLE_OPENSSL=ON","-DEVENT__DISABLE_THREAD_SUPPORT=ON","-DEVENT__DISABLE_DEBUG_MODE=ON","-DEVENT__DISABLE_MM_REPLACEMENT=ON"]
    steps:
    - uses: actions/checkout@v1
    - name: install depend
      run: |
        sudo apt install zlib1g-dev
        sudo apt install libssl-dev
        sudo apt install build-essential
        sudo apt install automake
        sudo apt install autoconf
        sudo apt install cmake
        sudo apt install lcov
    - name: build and test
      env:
        CC: gcc
      shell: bash
      run: |
        # matrix config
        # build and test
          export
          CTEST_PARALLEL_LEVEL=1
          CTEST_OUTPUT_ON_FAILURE=1;
          mkdir build &&
          cd build &&
          pwd &&
          cmake .. ${{ matrix.EVENT_CMAKE_OPTIONS }};
          if [ "$TEST_EXPORT" == "STATIC" ]; then
            cmake --build .;
            sudo python3 ../test-export/test-export.py static;
          elif [ "$TEST_EXPORT" == "SHARED" ]; then
            cmake --build .;
            sudo python3 ../test-export/test-export.py shared;
          else
            cmake --build . --target verify;
          fi
        fi
        if [ "$TOOL" == "doxygen" ]; then
          eval "$(ssh-agent -s)";
          openssl aes-256-cbc
            -K $encrypted_82aa789583ed_key
            -iv $encrypted_82aa789583ed_iv
            -in .github/travis-ci-key.enc
            -out .github/travis-ci-key -d;
          chmod 600 .github/travis-ci-key;
          ssh-add .github/travis-ci-key;
          mkdir build &&
          cd build &&
          cmake -DEVENT__DOXYGEN=ON .. &&
          cmake --build . --target doxygen;
          cd doxygen/html;
          git init;
          git add -f .;
          git commit -am "Update documentation ($TRAVIS_REPO_SLUG@$TRAVIS_COMMIT)";
          git push -f git@github.com:libevent/doc.git master;
        fi
