name: CI on linux

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - gha
    tags:
    - '*'

jobs:
  linux:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        pattern: [cmake0,cmake1]
    steps:
    - uses: actions/checkout@v1
    - name: install depend
      run: |
        sudo apt install zlib1g-dev
        sudo apt install libssl-dev
        sudo apt install build-essential
        sudo apt install automake
        sudo apt install autoconf
        sudo apt install cmake
        sudo apt install lcov
    - name: build and test
      env:
        CC: gcc
#         CXX: clang++
      shell: bash
      run: |
        pwd;
        BASE=`pwd`;
        mkdir ${BASE}/usr;
        # matrix config
        if [ ${{ matrix.pattern }} == cmake0 ]; then
          EVENT_BUILD_METHOD="cmake"
          EVENT_CMAKE_OPTIONS=""
          JOBS=1
        fi
        # build and test
        if [ "$EVENT_BUILD_METHOD" = "autotools" ]; then
          ./autogen.sh &&
          ./configure $EVENT_CONFIGURE_OPTIONS &&
          make &&
          make -j $JOBS verify;
        fi
        if [ "$EVENT_BUILD_METHOD" = "cmake" ]; then
          pwd
          export
          CTEST_PARALLEL_LEVEL=$JOBS
          CTEST_OUTPUT_ON_FAILURE=1;
          mkdir build &&
          cd build &&
          pwd &&
          cmake .. $EVENT_CMAKE_OPTIONS;
          if [ "$TEST_EXPORT" == "STATIC" ]; then
            cmake --build .;
            sudo python3 ../test-export/test-export.py static;
          elif [ "$TEST_EXPORT" == "SHARED" ]; then
            cmake --build .;
            sudo python3 ../test-export/test-export.py shared;
          else
            cmake --build . --target verify;
          fi
        fi
        if [ "$TOOL" == "doxygen" ]; then
          eval "$(ssh-agent -s)";
          openssl aes-256-cbc
            -K $encrypted_82aa789583ed_key
            -iv $encrypted_82aa789583ed_iv
            -in .github/travis-ci-key.enc
            -out .github/travis-ci-key -d;
          chmod 600 .github/travis-ci-key;
          ssh-add .github/travis-ci-key;
          mkdir build &&
          cd build &&
          cmake -DEVENT__DOXYGEN=ON .. &&
          cmake --build . --target doxygen;
          cd doxygen/html;
          git init;
          git add -f .;
          git commit -am "Update documentation ($TRAVIS_REPO_SLUG@$TRAVIS_COMMIT)";
          git push -f git@github.com:libevent/doc.git master;
        fi
